# Generated by Django 3.1.14 on 2023-12-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0010_auto_20231207_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='qty',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.IntegerField(default=None),
        ),
    ]
