# Generated by Django 3.1.14 on 2023-12-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0011_auto_20231207_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_qty',
            field=models.IntegerField(default=None),
        ),
    ]
